### ISSUE TITLE
Could this be in a setup file?

### ISSUE THREAD

**Issue by ariporad** [patrick-steele-idem/app-module-path-node#6]
Hi,

I really like your module, and have used it in the past, but I have a quick question for my current project.

I'd like to have a `setup.js` file which looks like this:

    require('babel/polyfill');
    require('app-module-path').addPath(__dirname);
    require('dotenv').load();

Then in my index.js file:

    require('./setup');
    // something something something. This is a really cool file
    var http = require('http')
    // ...

Would that work?

**Comment by philidem** [comment]
@ariporad I'm almost certain that the line `require('app-module-path').addPath(__dirname);` still needs to be in the entry point of your NodeJS application due to how the `app-module-path` module hooks into the module loader.

If I have multiple entry points then add that line to each entry point file. For example if your application can be ran via `node server.js` and `node build.js` then add that line to `server.js` and `build.js`.

If you know of a way to modify `app-module-path` so that it can add a search path directory while in a non-entry point file then please let us know. Otherwise, I think we can close this issue with the answer that putting `require('app-module-path').addPath(__dirname);` in `setup.js` in your example will not work. You will need to add that line to `index.js`.

**Comment by ariporad** [comment]
I'm working on a test for it, I'll let you know tomorrow morning.



Thanks!Ari

**Comment by ariporad** [comment]
I just tested it, it appears to work. You can see the results here: https://github.com/ariporad/test-app-module-path-in-setup-file

**Comment by philidem** [comment]
@ariporad maybe I'm missing something but your test project doesn't have a `setup.js` file. The line that uses `app-module-path` is in `src/index.js` which I assume is the entry point. Is this what you intended for your test?

**Comment by patrick-steele-idem** [comment]
I would actually expect it to work since `app-module-path` walks up the require tree to update the paths for already loaded parent modules using the following code:

https://github.com/patrick-steele-idem/app-module-path-node/blob/a9831ce467c193149a2712f3ce4b4aa5d8a583b8/lib/index.js#L38-L41

That was a later code change, but it is something that is supported. So to answer your question: Yes, it can be in a `setup.js` file.

I'm going to go ahead and close this issue, but feel free to comment or open another issue if you have other questions or concerns. Thanks.
